# Generated by Django 3.1.7 on 2021-02-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('memo', models.TextField()),
                ('slack_ID', models.CharField(max_length=40)),
                ('other_ID', models.TextField()),
                ('univercity', models.CharField(max_length=100)),
            ],
        ),
    ]
