# Generated by Django 3.1.7 on 2021-02-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210227_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='other_ID',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account_info',
            name='slack_ID',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='account_info',
            name='univercity',
            field=models.CharField(default='', max_length=100),
        ),
    ]
